default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: donandres_db
  username: postgres
  password: sqlseguro

test:
  <<: *default
  database: tc-db-test
  username:
  password:

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %> 
